name: User CI

env:
  WEBAPP_NAME: user-portal # set application's name
  AZURE_WEBAPP_NAME:  poc-mono-user-portal # set azure app name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set path to your web app project
  NODE_VERSION: "16"

on:
  push:
    branches: ["main"]
    paths: ["apps/user-portal/**"]

  pull_request:
    branches: ["main"]
    paths: ["apps/user-portal/**"]

  # Allow to run workflow manully
  workflow_dispatch:

jobs:
  build:
    name: Build User portal
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WEBAPP_NAME }}
          path: apps/${{ env.WEBAPP_NAME }}/dist

  staging:
    name: staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.WEBAPP_NAME }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_STAGING_POC_USER_PORTAL }}
          package: .
          # startup-command: pm2 serve /home/site/wwwroot --no-daemon --spa

  prod:
    name: Production
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: user-portal

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          startup-command: pm2 serve /home/site/wwwroot --no-daemon --spa
          # slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
